### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by XhmikosR**
* specify `fail-fast: false`
* update to `actions/setup-node@v2`
* fix indentation

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jakubpawlowicz we should probably run at least one version on Windows too. And/or update the readme line that says `tested on Linux, OS X, and Windows`

**Comment by jakubpawlowicz** [comment]
Yes we should. I can no longer test on OS X so I've just removed that. Re tests on Windows we should set it up.

**Comment by XhmikosR** [comment]
You can test OS X and Windows with Actions just fine :)

The easy way would be to just run the whole thing on all OS'es, even though it might be redundant running 4 Node.js version x 3 OS'es = 12 Actions.

**Comment by jakubpawlowicz** [comment]
I wasn't aware Actions support it. I wouldn't mind running them on Node.js 14 on OS X and Windows and the rest of them on Linux. Thoughts?

**Comment by XhmikosR** [comment]
Sounds good to me. I'll see if I can put something together in the next days and if we have a solid workflow file you can backport it to clean-css too.

**Comment by jakubpawlowicz** [comment]
Thanks, much appreciated! :+1:

**Pull request merged**
