### PR TITLE
Adds support for the --input-source-map flag.

### PR DESCRIPTION
**Pull request by ionutvmi**
Addresses https://github.com/jakubpawlowicz/clean-css-cli/issues/27

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
Great stuff @ionutvmi, please add that one change and I'll merge it.

**Comment by ionutvmi** [comment]
Hi @jakubpawlowicz ,
I don't see any comments on my side.
Can you please check if the review was submitted ?

**Comment by jakubpawlowicz** [comment]
Sorry, forgot to hit submit.

**Comment by ionutvmi** [comment]
The version has been updated

**Comment by jakubpawlowicz** [comment]
All good :+1:

**Comment by jakubpawlowicz** [comment]
It's out in v4.3.0. Thanks again @ionutvmi for your contribution!

**Pull request merged**
